trigger:
- master

pr:
- master

jobs:
- job: build_test_windows
  displayName: Build and Test on Windows
  timeoutInMinutes: 60

  strategy:
    maxParallel: 16
    matrix:
      VS2019_Win32:
        vm_image: windows-2019
        build_type: Release
        platform: Win32
        toolset: v142

  pool:
    vmImage: $(vm_image)

  steps:
    - powershell: |
        (Get-Content test\test_base.h) -replace 'DefaultEndpointsProtocol=https;', "$Env:MAPPED_TEST_CONFIGURATION" | Out-File -encoding ASCII test\test_base.h
        (Get-Content adls\test\adls_test_base.h) -replace 'DefaultEndpointsProtocol=https;', "$Env:MAPPED_ADLS_TEST_CONFIGURATION" | Out-File -encoding ASCII adls\test\adls_test_base.h
      displayName: Set Test Configuration
      env:
        MAPPED_TEST_CONFIGURATION: $(test_configuration)
        MAPPED_ADLS_TEST_CONFIGURATION: $(adls_test_configuration)

    - powershell: |
        Invoke-WebRequest -Uri https://codeload.github.com/microsoft/vcpkg/zip/master -OutFile vcpkg-master.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("vcpkg-master.zip", "C:\")
        cd C:\vcpkg-master
        .\bootstrap-vcpkg.bat
        .\vcpkg install curl[winssl]:x86-windows catch2:x86-windows
        .\vcpkg export curl[winssl]:x86-windows --nuget
      displayName: Install Dependencies
      
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: 'C:/vcpkg-master/*.nupkg;!C:/vcpkg-master/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '216a8129-e82c-4424-8b40-bbd33b1490ab/1f926c1c-b765-4980-9756-6010f2c3a9f6'
        allowPackageConflicts: true

    - powershell: |
        cmake CMakeLists.txt -B$(Build.BinariesDirectory) -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -A $(platform) -T $(toolset)
        cmake --build $(Build.BinariesDirectory) --config $(build_type)

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: $(vm_image)-$(platform)-$(toolset)
        PathtoPublish: $(Build.BinariesDirectory)      

    - powershell: |        
        Remove-Item $(Build.BinariesDirectory) -Recurse -Force
        cmake CMakeLists.txt -B$(Build.BinariesDirectory) -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DBUILD_ADLS=ON -A $(platform) -T $(toolset)
        cmake --build $(Build.BinariesDirectory) --config $(build_type)
      displayName: Build
    
    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: $(vm_image)-$(platform)-$(toolset)-adls
        PathtoPublish: $(Build.BinariesDirectory)

    - powershell: |
        .\azure-storage-test.exe
      workingDirectory: $(Build.BinariesDirectory)\$(build_type)
      displayName: Run Tests
