trigger:
- master

pr:
- master

- job: build_test_windows
  displayName: Build and Test on Windows
  timeoutInMinutes: 60

  strategy:
    maxParallel: 16
    matrix:
      VS2015:
        vm_image: vs2017-win2016
        build_type: Release
        platform: x64
        toolset: v140
      VS2017:
        vm_image: vs2017-win2016
        build_type: Release
        platform: x64
        toolset: v141
      VS2017_WIN32:
        vm_image: vs2017-win2016
        build_type: Debug
        platform: Win32
        toolset: v141
      VS2019:
        vm_image: windows-2019
        build_type: Debug
        platform: x64
        toolset: v142

  pool:
    vmImage: $(vm_image)

  steps:
    - powershell: |
        (Get-Content test\test_base.h) -replace 'DefaultEndpointsProtocol=https;', "$Env:MAPPED_TEST_CONFIGURATION" | Out-File -encoding ASCII test\test_base.h
        (Get-Content adls\test\adls_test_base.h) -replace 'DefaultEndpointsProtocol=https;', "$Env:MAPPED_ADLS_TEST_CONFIGURATION" | Out-File -encoding ASCII adls\test\adls_test_base.h
      displayName: Set Test Configuration
      env:
        MAPPED_TEST_CONFIGURATION: $(test_configuration)
        MAPPED_ADLS_TEST_CONFIGURATION: $(adls_test_configuration)

    - powershell: |
        Invoke-WebRequest -Uri https://codeload.github.com/microsoft/vcpkg/zip/master -OutFile vcpkg-master.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("vcpkg-master.zip", "C:\")
        cd C:\vcpkg-master
        .\bootstrap-vcpkg.bat
        .\vcpkg install curl[winssl]:x86-windows curl[winssl]:x64-windows catch2:x86-windows catch2:x64-windows
      displayName: Install Dependencies

    - powershell: |
        cmake CMakeLists.txt -B$(Build.BinariesDirectory) -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -A $(platform) -T $(toolset)
        cmake --build $(Build.BinariesDirectory) --config $(build_type)
        Remove-Item $(Build.BinariesDirectory) -Recurse -Force
        cmake CMakeLists.txt -B$(Build.BinariesDirectory) -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DBUILD_ADLS=ON -A $(platform) -T $(toolset)
        cmake --build $(Build.BinariesDirectory) --config $(build_type)
      displayName: Build

    - powershell: |
        .\azure-storage-test.exe
      workingDirectory: $(Build.BinariesDirectory)\$(build_type)
      displayName: Run Tests
